# Generated by Django 5.2.13 on 2026-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='clicks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
