# Generated by Django 5.2.13 on 2026-05-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_clicks_count_listing_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='clicks_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_promoted',
        ),
        migrations.AddField(
            model_name='listing',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
