# Generated by Django 5.2.13 on 2026-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
