# Generated by Django 5.2.13 on 2026-05-03 02:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_livestream_whatsapp_group_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='liveorder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='liveorder',
            name='live',
        ),
        migrations.RemoveField(
            model_name='liveorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='products',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='account',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='listing',
        ),
        migrations.DeleteModel(
            name='LiveComment',
        ),
        migrations.DeleteModel(
            name='LiveOrder',
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
    ]
