# Generated by Django 5.2.13 on 2026-04-30 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('buyer_name', models.CharField(blank=True, max_length=150)),
                ('seller_name', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('shipping_photos', models.TextField(blank=True, null=True)),
                ('delivery_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payé - Fonds bloqués'), ('shipping', 'En cours de livraison'), ('completed', 'Complété'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
