# Generated by Django 5.2.13 on 2026-05-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='listing_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='listing_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
