# Generated by Django 5.2.13 on 2026-05-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_escrowtransaction_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrowtransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='escrowtransaction',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='escrowtransaction',
            name='shipping_photos',
        ),
        migrations.RemoveField(
            model_name='escrowtransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='buyer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='listing_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='listing_title',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='reference',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='seller_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_payment', 'En attente de paiement'), ('paid', 'Payé'), ('shipping', 'Expédié'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('disputed', 'Litige')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
