# Generated by Django 5.2.13 on 2026-05-03 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_alter_escrowtransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('moov_money', 'Moov Money'), ('card', 'Carte bancaire')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
