# Generated by Django 5.2.13 on 2026-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_notification_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='RechargeTransaction',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='escrowtransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='delivery_company',
            field=models.CharField(blank=True, choices=[('avs', 'AVS TRANSPORT'), ('utb', 'UTB'), ('tsr', 'TSR'), ('sbta', 'SBTA'), ('ocalm', '🚴 Livreur OCALM')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='otp_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
