# Generated by Django 5.2.13 on 2026-05-03 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_delete_notification_delete_rechargetransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('new_order', '📦 Nouvelle commande'), ('payment', '💰 Paiement reçu'), ('shipping', '🚚 Colis expédié'), ('delivered', '✅ Livraison confirmée'), ('low_stock', '⚠️ Stock faible'), ('review', '⭐ Nouvel avis')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
