# Generated by Django 5.2.13 on 2026-05-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
